### PR TITLE
Clarify resend tutorial instructions

### PR DESCRIPTION
**Pull request by Bal2018**
**Issue #861 :** 

Instructions have been altered to ensure user knows what to do to complete task.  

Altered file `zap-hud/src/main/zapHomeFiles/hudtutorial/en_GB/Resend.task.html
`

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks!
You'll need to sign off your changes to pass the DCO check - see the Details link to the right hand side of the failing check.

**Comment by thc202** [comment]
Changelog should be updated.

**Comment by Bal2018** [comment]
After further investigation I found that I am having problems with my local ZAP setup and now can not reproduce the issue.  Ooops

**Comment by kingthorin** [comment]
The terminology change is probably still a good move.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
