### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by zersiax**
This PR adds some ARIA properties to the current UI, making it easier for screenreaders to infer what particular components are meant to be doing. In particular:

- Some unlabeled controls are now labeled
- - Modals will behave more like native modals where screenreaders are concerned, which also adds a quick way to navigate to them from the frames, as currently modals that open don't redirect screenreader focus
- tablists and tabs now have the appropriate semantic roles.

While ARIA is generally discouraged in favor of using semantic, native HTML, the current incarnation of the HUD would require quite the significant rewrite to make depending on semantic HTML viable.
While I am reasonably certain this won't break anything, I was unable to get the project to build to verify this. Probably a good idea to quickly pull down the branch to see if I didn't break any Vue magic unintentionally. ;)

### CODE REVIEW

**Comment by psiinon** [comment]
Great - many thanks!

**Comment by psiinon** [comment]
Looks good to me :)
Sorry for the delay - was very distracted by ZAPCon.
Could you sign off your commit so that it passes the DCO check and also update the [changelog](https://github.com/zaproxy/zap-hud/blob/main/CHANGELOG.md)

**Comment by zersiax** [comment]
Just amended the final commit with --signoff, that should do it :)

**Comment by thc202** [comment]
Actually all commits need to be signed off.

**Comment by zersiax** [comment]
Not entirely sure how to get that commit to sign off retroactively, I already did what the DCO check suggests, but it seems one commit, a0ab062, did not get signed off on by following that suggestion. what am I missing here?

**Comment by kingthorin** [comment]
You’d have to do an interactive rebase to do each one, in which case you may as well just squash it down to a single signed off commit. (Then you’ll have to force push.)

**Comment by zersiax** [comment]
Yeah, got it. hashtag tryHarder and all that.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by thc202** [comment]
For the record I didn't manually test the change (CI has HUD tests though).

**Comment by psiinon** [comment]
I'm not getting any alerts shown in the HUD now :/
Will double check its not some other local issue...

**Comment by zersiax** [comment]
Yeah I wasn't able to manually test either, so ...very much cowboy coding, this. If this PR turns out to not work well, I might try fixing various things using a tampermonkey script instead

**Comment by psiinon** [comment]
Its ok, local problem :)
Looks like my dev branch is broken for the HUD, the current one fails too. Works fine on 2.10.0.
Also sanity checks with the weekly and thats fine too.

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Many thanks!
@zersiax what name + link or twitter acc should we use for you in the credits? 
https://www.zaproxy.org/docs/desktop/credits/

**Comment by zersiax** [comment]
oh, just Florian Beijers (https://twitter.com/zersiax) is fine :)

**Comment by psiinon** [comment]
https://github.com/zaproxy/zap-core-help/pull/353 :)

**Pull request merged**
