### PR TITLE
Remove stale add-ons when building

### PR DESCRIPTION
**Pull request by thc202**
Change `assembleZapAddOn` to remove stale add-ons, to ensure ZAP loads
the add-on built.

### CODE REVIEW

**Comment by kingthorin** [comment]
Build failed?

**Comment by thc202** [comment]
Yes, but it's unrelated to these changes, the tutorial tests fail sometimes (restarted the failing job).

**Comment by thc202** [comment]
All passing now.

**Comment by dscrobonia** [comment]
I haven't looked too much into the selenium tests, but is there a reason why they fail sometimes? Is there a way we can make those more reliable? I know @psiinon did a ton of work getting those up, so I think it would be cool if we could make those trustworthy. Right now they don't really provide me value because if they fail I can't trust taht something is actually wrong.

**Pull request merged**
