### PR TITLE
Prettier peer dependency lint warning resolved

### LINKED ISSUE #608: Fix lint warnings
The following rules were set to "warn" so that we could focus on more important issues, but these should all be fixed as well:

- [ ] no-negated-condition
- [ ] no-unused-vars
- [ ] prefer-destructuring
- [ ] unicorn/no-for-loop
- [ ] unicorn/prefer-includes
- [ ] unicorn/prefer-string-slice
- [ ] unicorn/filename-case
- [ ] unicorn/prefer-query-selector

The overrides are defined in https://github.com/zaproxy/zap-hud/blob/develop/package.json#L54-L63 (the lines may change in time)

### PR DESCRIPTION
**Pull request by njmulsqb**
Signed-off-by: njmulsqb <najamulsaqib@tutamail.com>

Hi @psiinon,

I have resolved the prettier peer dependency (lint warning)

There are other warnings as well, if this PR gets merged I'll look how can I resolve rest of the warnings, so it partially resolves #608

### CODE REVIEW

**Comment by thc202** [comment]
Where are you seeing that warning?

**Comment by njmulsqb** [comment]
> Where are you seeing that warning?

I am seeing this when building zap hud.
image

**Comment by thc202** [comment]
Which commit? The CI build is not showing that:
https://github.com/zaproxy/zap-hud/runs/3618514889#step:5:46

**Comment by njmulsqb** [comment]
> Which commit? The CI build is not showing that:
> https://github.com/zaproxy/zap-hud/runs/3618514889#step:5:46

No idea, I just took the fresh clone of zap-hud and it was appearing at my end

**Pull request closed without merging**
