### PR TITLE
Lint the JavaScript

### PR DESCRIPTION
**Pull request by psiinon**
Result of running `xo --fix`
Also added global vars to configs, resulting in:
```
  49 warnings
  298 errors
```
Down from 4000+ ;)
WIP as for some reason this prevents the HUD config dialog buttons from working :/

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
By a process of elimination the problem is with utils.js - I'll keep digging...

**Comment by psiinon** [comment]
Have fixed the HUD config issue - for some reason the change from addEventListenner to onmessage in utils.js messageFrame - no idea why yet :/
Still 'WIP' as further manual testing shows that the following components are still broken:

- Sites Tree
- Break
- Reply in Browser
- HTML Report

**Comment by psiinon** [comment]
Worked out the problem with help from @thc202 - looks like a big in xo - raised as https://github.com/xojs/xo/issues/400
The above issues now seem to be fixed but I want to do more manual testing to make sure.
xo now reports:
```
  49 warnings
  196 errors
```

**Comment by psiinon** [comment]
The build is failing for the same reason as before, will fix that.
And some bad replaces that @thc202 spotted...

**Comment by psiinon** [comment]
Have changed some of the errors we are less interested in into warnings.
```
xo --quiet

  src/main/zapHomeFiles/hud/drawer.js:111:5
  ✖  111:5   tabsDetails is not defined.    no-undef
  ✖  111:32  tabsDetails is not defined.    no-undef
  ✖  220:5   tabsDetails is not defined.    no-undef
  ✖  220:32  tabsDetails is not defined.    no-undef

  src/main/zapHomeFiles/hud/management.js:33:8
  ✖   33:8   dontShowAgain is not defined.  no-undef

  src/main/zapHomeFiles/hud/tools/commonAlerts.js:64:6
  ✖   64:6   showAlerts is not defined.     no-undef

  6 errors
```
All of those are defined by Vue.

**Comment by psiinon** [comment]
Manual testing completed - ready for review.

**Comment by psiinon** [comment]
Tweaked so that xo should be now enabled on this repo (thanks @thc202 :)

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
