### PR TITLE
Just warn on lint unicorn/prefer-ternary

### PR DESCRIPTION
**Pull request by psiinon**
To fix https://travis-ci.com/github/zaproxy/zap-hud/jobs/442226410
Not sure why its failing on that PR and not others, but only really want to warn on this anyway..

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
This will have to be added in the other PR, it's a new rule.

Why "suppress" instead of changing the code? It would be more clear that's being initialised the variable.

**Comment by psiinon** [comment]
TBH I think:
```
		if (url.indexOf('://') > -1) {
			hostname = url.split('/')[2];
		} else {
			hostname = url.split('/')[0];
		}
```
is easier to read than 
```
		let hostname = url.indexOf('://') > -1 ? url.split('/')[2] : hostname = url.split('/')[0];
```
but happy to change that if I'm in the minoroty...

**Comment by thc202** [comment]
I prefer the later, but don't mind keeping what we have now. If we don't want the rule it's probably better to just disable than warn.

**Comment by thc202** [comment]
Closing this one as the change needs to be applied in #840. Could you apply the change there?

**Pull request closed without merging**
