### PR TITLE
Prepare for next release

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by kingthorin** [comment]
There's something wrong here, one file shows 0.9.0 the other 0.10.0

**Comment by psiinon** [comment]
I think thats normal isnt it? 9 is the current version, 10 will be the next one (but I could be wrong) @thc202 ?

**Comment by thc202** [comment]
Right.

**Comment by kingthorin** [comment]
Sorry was reading it as added content not just shifted...

**Comment by psiinon** [comment]
But it sounds like I've messed up one of the other commits so I'll look at this again

**Comment by psiinon** [comment]
Hopefully fixed now thanks again to @thc202 :)

**Pull request merged**
