### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kingthorin**
Minor corrections and adaptations.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
The DCO check is failing.

**Comment by kingthorin** [comment]
Will tweak it.

**Comment by kingthorin** [comment]
DCO fixed, rebased, etc.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
