### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by nayrangnu**
Just a grammar mistake ("ZAP find" should be "ZAP finds")

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Tks

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by thc202** [comment]
Could you also update the changelog?

**Comment by thc202** [comment]
@nayrangnu are you able to address the previous comments?

**Comment by thc202** [comment]
Updated the changelog and set DCO to pass (just a typo fix).

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
