### PR TITLE
Lint JavaScript

### PR DESCRIPTION
**Pull request by psiinon**
Result of `xo --fix`

Using the default options - happy to change that, but just wanted to see if this would pass the tests ;)

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by dscrobonia** [comment]
Rad! 🙌

**Comment by thc202** [comment]
The test `BadSiteUnitTest#cannotAccessWebSocketsUrlWhenLoadingSwAsScript` is now failing with `ZAP_HUD_FILES is not defined` (expected since the scope of `ZAP_HUD_FILES` has changed?).

**Comment by psiinon** [comment]
Yeah, I'll look into it :)

**Comment by psiinon** [comment]
Lets see if that works...

**Comment by psiinon** [comment]
ugh, format issue :P

**Pull request merged**
